OpenMined/omui

omui/src/components/alert-box/alert-box.tsx
Typescript types re-evaluation: `AlertBox`
n/a
=> Types: AlertBox

omui/src/components/alert/alert.tsx
Typescript types re-evaluation: `Alert`
n/a
=> Types: Alert

omui/src/components/accordion/accordion.tsx
Typescript types re-evaluation: `Accordion`
n/a
=> Types: Accordion

omui/src/components/avatar/avatar.tsx
Typescript types re-evaluation: `Avatar`
Also:
- The `badge` property only supports the theme colors.
n/a
=> Types: Avatar

omui/src/components/breadcrumb/breadcrumb.tsx
Typescript types re-evaluation: `Breadcrumb`
n/a
=> Types: Breadcrumb

omui/src/components/embed/embed.tsx
Typescript types re-evaluation: `Embed`
n/a
=> Types: Embed

README.md
Create a better readme [based on this readme template](https://github.com/OpenMined/.github/blob/master/README-TEMPLATE.md)
=> Create a better README

omui/src/components/image/image.tsx
Typescript types re-evaluation: `Image`
n/a
=> Types: Image

omui/src/components/input/input.tsx, omui/src/components/input/pin-input.tsx
Typescript types re-evaluation: `Input`
- Removed unnecessary prop. types covered by `React.ReactNode`
n/a
=> Types: Input

omui/package.json, omui/src/components/code/code.tsx, omui/yarn.lock
Setup eslint and prettier for lint e code formatting
Added 3 new scripts: `lint`, `lint:fix` and `format`
```
"lint": "eslint .",
"lint:fix": "eslint --fix .",
"format": "pretty-quick --staged"
```
"@typescript-eslint/eslint-plugin": "^3.4.0",
"@typescript-eslint/parser": "^3.4.0",
"babel-eslint": "10.1.0",
"eslint": "7.3.1",
"eslint-plugin-jest-dom": "^3.0.1",
"eslint-plugin-prettier": "^3.1.4",
"eslint-plugin-react": "^7.20.3",
"eslint-plugin-react-hooks": "^4.0.5",
"eslint-plugin-testing-library": "^3.3.1"
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.
=> Setup eslint + prettier

omui/src/components/list/list.stories.js, omui/src/components/list/list.tsx
Typescript types re-evaluation: `List`
- Removed `//@ts-ignore` by updating the types and adding the possible values.
n/a
=> Types: Fixed typescript issues in List

omui/.eslintignore, omui/.eslintrc
=> add eslint config files

omui/src/components/accordion/accordion.style.ts, omui/src/components/accordion/accordion.tsx, omui/src/components/accordion/index.ts, omui/src/theme/components.ts
Theme Refactoring: `Accordion` Component
=> Theme Refactoring: AccordionStyle

omui/src/components/alert/alert.style.ts, omui/src/components/alert/index.ts, omui/src/theme/components.ts
Theme Refactoring: `Alert` Component
=> Theme Refactoring: AlertStyle

omui/src/components/avatar/avatar.style.ts, omui/src/components/avatar/index.ts, omui/src/theme/components.ts
Theme Refactoring: `Avatar` Component
=> Theme Refactoring: AvatarStyle

omui/src/components/badge/badge.style.ts, omui/src/components/badge/index.ts, omui/src/theme/components.ts
Theme Refactoring: `Badge` Component
=> Theme Refactoring: BadgeStyle

omui/src/components/button/button.style.ts, omui/src/components/button/index.ts, omui/src/theme/components.ts
Theme Refactoring: `Button` Component
=> Theme Refactoring: ButtonStyle

omui/src/components/tag/index.ts, omui/src/components/tag/tag.style.ts, omui/src/helpers/get-theme.ts, omui/src/theme/components.ts
Theme Refactoring: `Tag` Component
=> theme refactoring: TagStyle

omui/src/components/checkbox/checkbox.style.ts, omui/src/components/checkbox/index.ts, omui/src/components/radio/radio.style.ts, omui/src/theme/components.ts
Theme Refactoring: `Checkbox` Component
=> Theme Refactoring: CheckboxStyle

omui/src/components/radio/index.ts, omui/src/components/radio/radio.style.ts, omui/src/theme/components.ts
Theme Refactoring: `Radio` Component
=> Theme Refactoring: RadioStyle

omui/src/components/close-button/close-button.style.ts, omui/src/components/close-button/index.ts, omui/src/theme/components.ts
Theme Refactoring: `CloseButton` Component
=> Theme Refactoring: CloseButtonStyle

omui/src/components/editable/editable.style.ts, omui/src/theme/components.ts
Theme Refactoring: `Editable` Component
=> Theme Refactoring: EditableStyle

omui/src/components/form-control/form-control.style.ts, omui/src/theme/components.ts
Theme Refactoring: `FormControl` Component
=> Theme Refactoring: FormControlStyle

omui/src/components/heading/heading.style.ts, omui/src/components/heading/index.ts, omui/src/theme/components.ts
Theme Refactoring: `Heading` Component
=> Theme Refactoring: Heading

omui/src/components/input/index.ts, omui/src/components/input/number-input.style.ts, omui/src/theme/components.ts
Theme Refactoring: `NumberInput` Component
=> Theme Refactoring: NumberInput

omui/src/components/input/index.ts, omui/src/components/input/pin-input.style.ts, omui/src/theme/components.ts
Theme Refactoring: `PinInput` Component
=> Theme Refactoring: PinInputStyle

.github/workflows/chromatic.yml, omui/package.json, omui/src/index.ts
=> Trying new action

omui/package.json, omui/yarn.lock
Bump Chakra UI version to `1.0.0-rc.2`
```
"@chakra-ui/core": "1.0.0-rc.2",
"@chakra-ui/system": "1.0.0-rc.2",
"@chakra-ui/theme": "1.0.0-rc.2",
"@chakra-ui/theme-tools": "1.0.0-rc.2",
"@chakra-ui/icons": "1.0.0-rc.2"
```
=> bump chakra version to 1.0.0-rc.2

omui/package.json, omui/src/components/flex/flex.stories.js, omui/src/theme/index.ts, omui/yarn.lock
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
"@chakra-ui/core": "1.0.0-rc.3",	    "@chakra-ui/core": "1.0.0-rc.7",
"@chakra-ui/system": "1.0.0-rc.3",	    "@chakra-ui/system": "1.0.0-rc.7",
"@chakra-ui/theme": "1.0.0-rc.3",	    "@chakra-ui/theme": "1.0.0-rc.7",
"@chakra-ui/theme-tools": "1.0.0-rc.3",	    "@chakra-ui/theme-tools": "1.0.0-rc.7",
"@chakra-ui/icons": "1.0.0-rc.3",	    "@chakra-ui/icons": "1.0.0-rc.7"
- Added new dependency (required for using chakra)
```
"framer-motion": …
```
=> Bump chakra-ui version to 1.0.0-rc.7

omui/src/components/tabs/index.ts, omui/src/index.ts
=> fix tab exports
